services:
  - type: web
    name: AuraLink-AI-Accessibility-System
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
